### PR TITLE
feat: add support for `pathlib.Path` type

### PR DESCRIPTION
**Pull request by jpoppe**
I am looking for a replacement for `ConfZ` which uses native `dataclasses` instead of `Pydantic`. Ported my first (simple) configuration to `dataconf` and was missing `Path` (de)serialization/type support.

### CODE REVIEW

**Comment by jpoppe** [comment]
After thinking a bit more about this and playing with `dataconf` I realized this pull request is not complete to match the current `datconf` flow, will maybe come back to this.

**Comment by zifeo** [comment]
@jpoppe can you elaborate what you feel is missing?

**Comment by jpoppe** [comment]
I reopened and think It should be fine to merge after a played a bit more, *dataconf* is not what I was exactly looking for, still nice work ;)

**Review by zifeo — APPROVED** [review]

**Comment by zifeo** [comment]
@jpoppe indeed, not a serialization/deserialization lib. Thanks for the contrib.

**Pull request merged**
