### PR TITLE
Add mypy compatibility

### PR DESCRIPTION
**Pull request by zifeo**

### CODE REVIEW

**Comment by dwsmith1983** [comment]
@zifeo are there any tests for this update?

**Review by dwsmith1983 — COMMENTED** [review]
Do we need any test for this update?

**Comment by zifeo** [comment]
@dwsmith1983 It could be tested by installing the package into an empty poetry project with mypy CLI as part of a test. However the risk of regression is low and I feel this might be too heavy for now.

**Review by dwsmith1983 — APPROVED** [review]

**Comment by dwsmith1983** [comment]
Add mypy #minor bump

**Pull request merged**
