### PR TITLE
chore!: update pyparsing and pyhocon

### PR DESCRIPTION
**Pull request by lannuttia**
This PR was originally intended to just update pyparsing but it appears that in order to do that, I also have to update pyhocon.

The upgrade went relatively smoothly however I did have to slightly modify a single test that utilizes pyhocon. I'm not super familiar with HOCON but the fact that a space inserted before the newline character fixes the broken test seems to suggest that there is a bug with pyhocon itself.

The test in question can be found [here](https://github.com/zifeo/dataconf/commit/80760806e647525a59d4b036816c4907eee96671).

### CODE REVIEW

**Comment by zifeo** [comment]
@lannuttia thanks for giving a try? Did you find the upstream issue? If so, we will give a go for the upgrade and inform the user.

**Comment by lannuttia** [comment]
I have created an issue against pyhocon [here](https://github.com/chimpler/pyhocon/issues/324).

**Comment by lannuttia** [comment]
Looks like the issue I reported against pyhocon has been resolved [here](https://github.com/chimpler/pyhocon/issues/324#issuecomment-2128253883). I suspect that if we upgrade to the patched version, we should be able to put the tests back the way they were before and they should pass again.

**Comment by lannuttia** [comment]
@zifeo ^

**Comment by zifeo** [comment]
@lannuttia Yes! Let's see wether that gets merged and released, the library maintainers were not that active last year...

**Pull request merged**
