### PR TITLE
Dev/add coverage badge

### PR DESCRIPTION
**Pull request by dwsmith1983**
Added coverage badge to README and instructions for generating new badges when code base is updated.

### CODE REVIEW

**Comment by dwsmith1983** [comment]
@zifeo can we automate this with test and release? I see it isn't calling poetry to run pytest. If we call pytest with --cov, coverage xml, and genbadge coverage, we can auto update the badge.svg during testing. 

I guess a separate questions is can we write the update svg file to the repo after testing?

**Comment by zifeo** [comment]
@dwsmith1983 Great! I see multiple options:
- we use some pre-commit and manage the badge locally as suggested in this pull request
- we use [coveralls](https://coveralls.io) which is free for open source projet and use this [github-action](https://github.com/marketplace/actions/coveralls-github-action)
- we only use coverage information in pull request with action similar to [this one](https://github.com/MishaKav/pytest-coverage-comment)

**Comment by dwsmith1983** [comment]
> @dwsmith1983 Great! I see multiple options:
> 
> * we use some pre-commit and manage the badge locally as suggested in this pull request
> * we use [coveralls](https://coveralls.io) which is free for open source projet and use this [github-action](https://github.com/marketplace/actions/coveralls-github-action)
> * we only use coverage information in pull request with action similar to [this one](https://github.com/MishaKav/pytest-coverage-comment)

The github action looks nice as it shows the coverage.

**Review by zifeo — CHANGES_REQUESTED** [review]
I have given another try and believe the best approach is not to store the badge locally. Rather, I have already configured codecov.io and added the secret in the pipeline. Getting the coverage should be as easy [this](https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/):

```
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3
```
Can you also rebase please?

**Comment by zifeo** [comment]
Closing for now

**Pull request closed without merging**
